site_name: Eron Lloyd
site_url: https://www.eronlloyd.com
theme:
  palette:
    primary: green
  name: material
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eronlloyd
      name: Eron Lloyd on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eronlloyd
      name: Eron Lloyd on LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://www.x.com/eronlloyd
      name: Eron Lloyd on X (Twitter)
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/eronlloyd
      name: Eron Lloyd on Instagram
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@eronlloyd
      name: Eron Lloyd on Threads
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/eronlloyd.bsky.social
      name: Eron Lloyd on Bluesky
  consent:
    title: Cookie consent
    description: >- 

      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - blog:
      post_url_format: "{slug}"
  - tags
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - CV: 'cv/index.md'
    - Projects: 'projects/index.md'
    - Blog:
      - blog/index.md

