site_name: Eron Lloyd
site_url: https://www.eronlloyd.com
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eronlloyd
      name: Eron Lloyd on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eronlloyd
      name: Eron Lloyd on LinkedIn
  consent:
    title: Cookie consent
    description: >- 

      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
plugins:
  - search
  - blog
  - tags
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Blog:
      - blog/index.md

